"""metricas forms"""

from django import forms

from metricas.models import *


class MetricasRiesgoForm(forms.ModelForm):

    class Meta:
        model = MetricasRiesgoModel

        fields = [
                "numero_escenarios",
                "horizonte_riesgo",
                "q",
                "bps",
                "fechacorte",
                "lyot",
                "sim",
                "ref",
                "par",
                "lylp",
                "cat",
                "vec",
                "rr7port",
                "vecpip",
                "curpip",
                "rr7inmu",
                "rr4imprec",
                "histocurvas",
                "histocurvasReportes",
                "histospread",
                "histoTC",
                "histoVaR_Subgrupos",
                "histoVaR_Instrumentos",
                "cartera_BT",
                "ruta_Layout",
                "ruta_DeuCamb",
                "ruta_VectorPrecios",
                "ruta_Parametros",
                "excluye_Capitales_NO_PiP",
                "excluye_Deuda_califD",
                "horizonte_Diario",
                "horizonte_Semanal",
                "horizonte_Mensual",
                "horizonte_Anual",

        ]
        labels = {
            "numero_escenarios":"Número de escenarios (entero de 1000 a 10000)",
            "horizonte_riesgo":"Horizonte de riesgo",
            "q":"Nivel de confianza (positivo menor a 1)",
            "bps":"Puntos base",
            "fechacorte":"Fecha de corte",
            "lyot":"LYOT.mat",
            "sim":"SIM.mat",
            "ref":"REF.mat",
            "par":"PAR.mat",
            "lylp":"RR4LYLPS.mat",
            "cat":"CAT.mat",
            "vec":"VEC.mat",
            "rr7port":"RR7Portafolios.xlsx",
            "vecpip":"VectorPiP.xls",
            "curpip":"CurvasPiP.xls",
            "rr7inmu":"RR7EFITRINMU.txt",
            "rr4imprec":"RR4IMPREC.txt",
            "histocurvas":"HCurvas.csv",
            "histocurvasReportes":"HCurvasReportes.csv",
            "histospread":"HSpread.csv",
            "histoTC":"HTiposCambio.csv",
            "histoVaR_Subgrupos":"HVaR_Subgrupos.csv",
            "histoVaR_Instrumentos":"HVaR_Instrumentos",
            "cartera_BT":"Asociar cartera a proceso de Backtesting",
            "ruta_Layout":"Ruta Layoutglobal",
            "ruta_DeuCamb":"Ruta Parametros Deuda y Cambiario",
            "ruta_VectorPrecios":"Ruta Vector Precios",
            "ruta_Parametros":"Ruta Parametros Referencia",
            "excluye_Capitales_NO_PiP":"Excluir registros de Capitales no encontrados en VectorPiP.xls",
            "excluye_Deuda_califD":"Excluir registros de Deuda con calificacion D en VectorPiP.xls",
            "horizonte_Diario":"Diario",
            "horizonte_Semanal":"Semanal",
            "horizonte_Mensual":"Mensual",
            "horizonte_Anual":"Anual",
        }
        widgets = {
            "numero_escenarios":forms.TextInput(),
            "horizonte_riesgo":forms.Select(),
            "q":forms.TextInput(),
            "bps":forms.TextInput(),
            "fechacorte":forms.DateInput(format=('%Y-%m-%d'), attrs={'class':'datepicker'}),
            "lyot":forms.FileInput(attrs={"accept":".mat"}),
            "sim":forms.FileInput(attrs={"accept":".mat"}),
            "ref":forms.FileInput(attrs={"accept":".mat"}),
            "par":forms.FileInput(attrs={"accept":".mat"}),
            "lylp":forms.FileInput(attrs={"accept":".mat"}),
            "cat":forms.FileInput(attrs={"accept":".mat"}),
            "vec":forms.FileInput(attrs={"accept":".mat"}),
            "rr7port":forms.FileInput(attrs={"accept":".xlsx"}),
            "catcalif":forms.FileInput(attrs={"accept":".xlsx"}),
            "vecpip":forms.FileInput(attrs={"accept":".xls"}),
            "curpip":forms.FileInput(attrs={"accept":".xls"}),
            "rr7inmu":forms.FileInput(attrs={"accept":".txt"}),
            "rr4imprec":forms.FileInput(attrs={"accept":".txt"}),
            "histocurvas":forms.FileInput(attrs={"accept":".csv"}),
            "histocurvasReportes":forms.FileInput(attrs={"accept":".csv"}),
            "histospread":forms.FileInput(attrs={"accept":".csv"}),
            "histoTC":forms.FileInput(attrs={"accept":".csv"}),
            "rCredito":forms.CheckboxInput(attrs={'class':'filled-in'}),
            "rMercado":forms.CheckboxInput(attrs={'class':'filled-in'}),
            "histoVaR_Subgrupos":forms.FileInput(attrs={"accept":".csv"}),
            "histoVaR_Instrumentos":forms.FileInput(attrs={"accept":".csv"}),
            "cartera_BT":forms.CheckboxInput(attrs={'class':'filled-in'}),
            "ruta_Layout":forms.TextInput(),
            "ruta_DeuCamb":forms.TextInput(),
            "ruta_VectorPrecios":forms.TextInput(),
            "ruta_Parametros":forms.TextInput(),
            "excluye_Capitales_NO_PiP":forms.CheckboxInput(attrs={'class':'filled-in'}),
            "excluye_Deuda_califD":forms.CheckboxInput(attrs={'class':'filled-in'}),
            "horizonte_Diario":forms.CheckboxInput(attrs={'class':'filled-in'}),
            "horizonte_Semanal":forms.CheckboxInput(attrs={'class':'filled-in'}),
            "horizonte_Mensual":forms.CheckboxInput(attrs={'class':'filled-in'}),
            "horizonte_Anual":forms.CheckboxInput(attrs={'class':'filled-in'}),
        }

